### ISSUE TITLE
Figure out how ticketing works

### ISSUE THREAD

**Issue by jwpowell** [jwpowell/lark#1]
Figure out what a ticket is and how I can assign it to people other than me. Because that's called leadership.

**Comment by wspowell** [comment]
Work. Work. Work.

**Comment by jwpowell** [comment]
Do more work here.

**Comment by wspowell** [comment]
Typety typey.

**Comment by jwpowell** [comment]
You broke the build. You forgot a semicolon.

**Comment by wspowell** [comment]
D:

Fixed.

**Comment by jwpowell** [comment]
I'll allow it.
